#!/bin/bash
# dw-pgdjlgs: download tools from bin/ directory
BASE_URL="https://raw.githubusercontent.com/pgdjlgs/tols/main/bin"

if [[ $EUID -ne 0 ]]; then
   echo "error: root privileges required."
   exit 1
fi

TOOL=$1
if [ -z "$TOOL" ]; then
    echo "usage: sudo dw-pgdjlgs <tool_name>"
    exit 1
fi

echo "collecting $TOOL"
HTTP_STATUS=$(curl -# -L -o "/usr/local/bin/$TOOL" -w "%{http_code}" "$BASE_URL/$TOOL")

if [ "$HTTP_STATUS" -eq 200 ]; then
    chmod +x "/usr/local/bin/$TOOL"
    echo "successfully installed $TOOL."
else
    rm -f "/usr/local/bin/$TOOL"
    echo "error: status $HTTP_STATUS. tool not found in /bin."
fi
