#!/bin/bash
# dw-pgdjlgs - My Dynamic Package Manager
# made by pgdjlgs v1

TOOL=$1
VERSION=$2
REPO="pgdjlgs/tols"
LOCAL_BIN="/usr/local/bin"

# هل الادات مثبتة 
if [ -f "$LOCAL_BIN/$TOOL" ] && [ -z "$VERSION" ]; then
    echo "⚠️ Hey! '$TOOL' is already installed on your PC."
    echo "💡 If you want to update it, just run: up-pgdjlgs $TOOL"
    exit 0
fi

# اختيار الاصدار
if [ -z "$VERSION" ]; then
    TARGET_VERSION="main"
else
    TARGET_VERSION="$VERSION"
fi

# رابط التحميل
URL="https://raw.githubusercontent.com/$REPO/$TARGET_VERSION/bin/$TOOL"

echo "📡 Checking GitHub for $TOOL ($TARGET_VERSION)... please wait..."

# بدء التحميل 
sudo curl -s -L -f -o "$LOCAL_BIN/$TOOL" "$URL"

# التأكد من نجاح التحميل
if [ $? -eq 0 ]; then
    sudo chmod +x "$LOCAL_BIN/$TOOL"
    echo "✅ Awesome! $TOOL is ready to use now."
else
    echo "❌ Ops! Tool or Version not found inside my repo."
    echo "You can check available versions here: https://github.com/$REPO/tags"
    exit 1
fi
