#!/bin/bash

# التأكد من تشغيل الأمر بصلاحيات الروت
if [[ $EUID -ne 0 ]]; then
   echo "[-] لازم تشغل الأمر بـ sudo: sudo simplify"
   exit 1
fi

# البحث داخل مجلد core في المكان اللي واقف فيه المستخدم حالياً
echo "[*] جاري تبسيط أوامر المستودع وتحويلها لأوامر نظام حقيقية..."

for file in "$(pwd)"/core/*-pgdjlgs; do
    if [ -x "$file" ]; then
        full_name=$(basename "$file")
        short_name="${full_name%-pgdjlgs}"
        
        # عمل الرابط الرمزي في /usr/bin/
        ln -sf "$file" "/usr/bin/$short_name"
        
        echo "  [+] تم تفعيل الأمر الحقيقي بالنظام: $short_name"
    fi
done

echo "[+] انتهى! الأوامر المختصرة شقالة الحين في كامل النظام."
